
Config = {}

Config.Locale = 'th'

Config['esx_routers'] = {								-- เส้นทางกิจกรรมของทรัพยากร ESX Framework
	['server_shared_obj'] = 'esx:getSharedObject',		-- หาก es_extended เซิร์ฟเวอร์ของคุณ มีการแก้ไขชื่อกิจกรรมของทรัพยากร เพื่อป้องกันโปรแกรมโกงต่าง ๆ
	['client_shared_obj'] = 'esx:getSharedObject',		-- คุณสามารถแก้ไขการตั้งค่าในส่วนนี้ให้ตรงกับชื่อกิจกรรมของทรัพยากรนั้น ๆ ได้
	['server_player_load'] = 'esx:playerLoaded'			-- หมายเหตุ: ห้ามแก้ไขการตั้งค่าในส่วนนี้โดยเด็ดขาด หากคุณไม่เข้าใจว่าสิ่งนี้คืออะไร เพราะอาจจะทำให้ทรัพยากรเกิดข้อผิดพลาดได้
}

Config['identifier_license'] = false					-- เปิดใช้งาน ตรวจสอบ R* License แทน Steam (true = ใช้ตัวระบุ R* License | false = ใช้ตัวระบุ Steam)
														-- หมายเหตุ: หากเปิดใช้งาน ตรวจสอบ R* License จำเป็นที่จะต้องใช้งาน es_extended เวอร์ชั่น 1.2.0 ขึ้นไป

Config['discord_role_whitelist'] = '1193183876634378243'		  	-- ระบุ รหัสบทบาท Whitelist ในกลุ่ม Discord ระบุเฉพาะ "ตัวเลข" เท่านั้น (วิธีการรับรหัส ให้พิมพ์ในกลุ่ม @ชื่อบทบาทไวริส แล้วเพิ่มเครื่องหมาย \ ไว้ข้างหน้า ยกตัวอย่าง: \@Whitelisted)
Config['discord_guild_id'] = '1193183876634378240'					-- ระบุ รหัสกลุ่ม Discord ของเซิร์ฟเวอร์
Config['discord_bot_token'] = 'MTE5MjM1MDM3NTY3NjczOTY3NA.GlvIAi.4IY5YX_Search 391vYkP8fEDuhAUkYzaU… 
on blockchair.coSearch m391vYkP8fEDuhAUkYza… 
on blockchair.coSearch mm391vYkP8fEDuhAUkYz… 
on blockchair.coSearch mmm391vYkP8fEDuhAUkY… 
on blockchair.coSearch mmmm391vYkP8fEDuhAUk… 
on blockchair.coSearch mmmmm391vYkP8fEDuhAU… 
on blockchair.coSearch mmmmmm391vYkP8fEDuhA… 
on blockchair.coSearch mmmmmmm391vYkP8fEDuh… 
on blockchair.coSearch mmmmmmmm391vYkP8fEDu… 
on blockchair.coSearch mmmmmmmmm391vYkP8fED… 
on blockchair.coSearch mmmmmmmmmm391vYkP8fE… 
on blockchair.coSearch mmmmmmmmmmm391vYkP8f… 
on blockchair.coSearch mmmmmmmmmmmm391vYkP8… 
on blockchair.coSearch mmmmmmmmmmmmm391vYkP… 
on blockchair.coSearch mmmmmmmmmmmmmm391vYk… 
on blockchair.coSearch mmmmmmmmmmmmmmm391vY… 
on blockchair.coSearch mmmmmmmmmmmmmmmm391v… 
on blockchair.coSearch mmmmmmmmmmmmmmmmm391… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmm39… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmm3… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.coSearch mmmmmmmmmmmmmmmmmmmm… 
on blockchair.commmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm391vYkP8fEDuhAUkYzaU5xOAfVmP5XM'				-- ระบุ Discord Bot Token ที่ใช้ตรวจสอบบทบาทภายในกลุ่ม Discord
														-- วิธีสร้าง Discord Bot สามารถดูได้ที่ https://docs.azael.dev/azael_dc-whitelisted.html

Config['discord_webhook_logs'] = 'https://discord.com/api/webhooks/1193195685256904775/koEJS1tzN8EYC8kMp_r49qwudBpMWV6VGpYWVpTwaEOyBEPSrU9oOCQhZiIlk8p0GkVb'			-- ระบุ Discord Webhook URL สำหรับเก็บข้อมูล Whitelist ของผู้เล่น
Config['discord_webhook_alert'] = 'https://discord.com/api/webhooks/1193195685256904775/koEJS1tzN8EYC8kMp_r49qwudBpMWV6VGpYWVpTwaEOyBEPSrU9oOCQhZiIlk8p0GkVb'		-- ระบุ Discord Webhook URL สำหรับการเเจ้งเตือนสถานะ Whitelist

Config['discord_down'] = false							-- เปิดใช้งาน ตรวจสอบ Whitelist ใน Database แทน ในกรณี Discord ล้ม (true = เปิดใช้งาน false = ปิดใช้งาน)
														-- ระบบจะทำการเช็คว่าผู้เล่นที่เชื่อมต่อเซิร์ฟเวอร์มีบัญชี Identifier ในตาราง azael_dc_whitelisted
														-- ในกรณีผู้เล่นที่ Admin พึ่งดำเนินการเพิ่มยศ หรือ บทบาท ในกลุ่ม Discord เเละ ยังไม่มีข้อมูลในฐานข้อมูลตาราง azael_dc_whitelisted ผู้เล่นจะไม่สามารถเชื่อมต่อกับเซิร์ฟเวอร์ได้ 
														-- ตรวจสอบสถานะ Discord ได้ที่ https://status.discordapp.com

Config['url_community'] = true                   		-- เปิดใช้งาน เเสดงลิ้งค์ชุมชน (true = เปิดใช้งาน | false เท่ากับ ปิดใช้งาน)
Config['url_community_link'] = 'https://discord.gg/fDY85g7jf4'	-- ระบุ ลิ้งค์ชุมชน ที่คุณต้องการ

Config['whitelist_expire'] = true						-- เปิดใช้งาน ตรวจสอบวันหมดอายุของ Whitelist (true = เปิดใช้งาน | false เท่ากับ ปิดใช้งาน)
Config['whitelist_give_day'] = 30						-- ระบุ จำนวนวันใช้งาน สำหรับการเชื่อมต่อเซิร์ฟเวอร์ในครั้งเเรกหลังจากที่เพิ่มยศ หรือ บทบาท Whitelist ให้ในกลุ่ม Discord

Config['whitelist_realtime'] = false						-- เปิดใช้งาน ตรวจสอบวันหมดอายุของ Whitelist เเละ สถานะการ Ban ของผู้เล่นภายในเกมส์ (true = เปิดใช้งาน | false เท่ากับ ปิดใช้งาน)
Config['whitelist_realtime_timer'] = 15					-- รุบุ เวลาในการตรวจสอบผู้เล่นที่อยู่ในเกมส์เเต่ละครั้ง (1 เท่ากับ 1 นาที เเนะนำ 15 นาที)

Config['whitelist_onhold'] = true						-- เปิดใช้งาน ตรวจผู้เล่นว่าเชื่อมต่อเซิร์ฟเวอร์ติดต่อกันตามวันที่เรากำหนดหรือไม่ หากไม่เชื่อมต่อเซิร์ฟเวอร์ติดต่อกัน ระบบจะทำการระงับ Whitelist ไว้ชั่วคราว (true = เปิดใช้งาน | false เท่ากับ ปิดใช้งาน)
Config['whitelist_onhold_limit'] = 30                    -- ระบุ จำนวนวันในการตรวจสอบผู้เล่น หากผู้เล่นไม่เชื่อมต่อเซิร์ฟเวอร์ติดต่อกันตามจำนวนวันที่ระบุ Whitelist ผู้เล่นจะถูกระงับโดยทันที (บทบาทในกลุ่ม Discord ยังคงสถานะ Whitelist)
Config['whitelist_onhold_queue_point'] = false			-- เปิดใช้งาน ตรวจสอบผู้เล่นที่มี VIP Queue Points ที่ไม่เชื่อมต่อเซิร์ฟเวอร์ติดต่อกัน (true เท่ากับ เปิดใช้งาน false เท่ากับ ปิดใช้งาน)

														-- Queue Connection by Rocademption Edited by Azael Dev
Config['queue_rocademption'] = true						-- เปิดใช้งาน Queue - Rocademption (true = เปิดใช้งาน | false เท่ากับ ปิดใช้งาน)
Config['queue_point_expire'] = true             		-- เปิดใช้งาน VIP Queue Points หมดอายุ (true = เปิดใช้งาน | false เท่ากับ ปิดใช้งาน)
Config['queue_max_server_slots'] = 256					-- ระบุ จำนวนผู้เล่นสูงสุดของเซิร์ฟเวอร์ หากเปิดใช้งาน One Sync ให้ระบุ 256 (ผู้เล่นมากกว่า 32 slot)
Config['queue_anti_spam_timer'] = 5						-- ระบุ เวลาดีเลย์การเชื่อมต่อกับเซิร์ฟเวอร์ เป็น วินาที
Config['queue_timer_refresh_client'] = 5				-- ระบุ เวลาอัพเดทข้อความ (อิโมจิ) เป็น วินาที
Config['queue_timer_check_places'] = 3					-- ระบุ เวลาในการตรวจสอบผู้เล่นที่ทำการเชื่อมต่อ เป็น วินาที
Config['queue_timer_update_points']	= 6					-- ระบุ เวลาในการอัพเดท Points ให้ผู้เล่นระหว่างรอคิว (ไม่มีผลกับ Points ในฐานข้อมูล)
Config['queue_add_points'] = 1							-- ระบุ จำนวน Points ที่ได้รับระหว่างรอคิวเชื่อมต่อเซิร์ฟเวอร์ (ไม่มีผลกับ Points ในฐานข้อมูล)
Config['queue_bonus_points'] = 25						-- ระบุ จำนวน Points ที่ได้รับสำหรับผู้ที่มีอีโมจิ 3 ตัว (ไม่มีผลกับ Points ในฐานข้อมูล)
